-- EX1. HackerRank
SELECT NAME FROM CITY
WHERE population > 120000 AND CountryCode = "USA"

-- EX2.
SELECT * FROM CITY
WHERE COUNTRYCODE = 'JPN'

-- EX3.
SELECT CITY, STATE FROM STATION

-- EX4.
SELECT CITY FROM STATION
WHERE CITY LIKE 'a%' OR CITY LIKE 'e%' OR CITY LIKE 'i%' OR CITY LIKE 'o%' OR CITY LIKE 'u%'

-- EX5.
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u'

-- EX6.
SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE 'a%' AND CITY NOT LIKE 'e%' AND CITY NOT LIKE 'i%' AND CITY NOT LIKE 'o%' AND CITY NOT LIKE 'u%'

-- EX7.
SELECT name FROM Employee
ORDER BY name

-- EX8.
SELECT name FROM Employee
WHERE salary > 2000 AND months < 10
ORDER BY employee_id





